### ISSUE TITLE
flask.current_app() throws exception

### ISSUE THREAD

**Issue by mdavis-xyz** [maarten-dp/requests-flask-adapter#4]
When using blueprints in Flask, you're supposed to call `flask.current_app()` to get the app object.

When I try that with this library, I get:

```
TypeError: Flask.__call__() missing 2 required positional arguments: 'environ' and 'start_response'
```

I think there's no request context. (Although this isn't the normal error message for that.)

Steps to reproduce:

```
from requests_flask_adapter import Session
from flask import Blueprint, Flask, current_app

app = Flask(__name__)
@app.route('/simple')
def simple():
    return ("Hello World", 200)

@app.route('/complex')
def complex():
    current_app()
    return ("Hello World", 200)

    
Session.register('http://my_app', app)
s = Session()

r=s.get('http://my_app/simple')
r.raise_for_status()

r=s.get('http://my_app/complex')
r.raise_for_status()
```

Run this script. It should pass.
It does not. The traceback is:

```
[2023-01-20 14:48:54,734] ERROR in app: Exception on /complex [GET]
Traceback (most recent call last):
  File "/Users/matthew/Documents/Syncthing/MacDefault/fast-unit-flask/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/matthew/Documents/Syncthing/MacDefault/fast-unit-flask/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/matthew/Documents/Syncthing/MacDefault/fast-unit-flask/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/matthew/Documents/Syncthing/MacDefault/fast-unit-flask/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/matthew/Documents/Syncthing/MacDefault/fast-unit-flask/mwe2.py", line 11, in complex
    current_app()
  File "/Users/matthew/Documents/Syncthing/MacDefault/fast-unit-flask/venv/lib/python3.10/site-packages/werkzeug/local.py", line 570, in <lambda>
    __call__ = _ProxyLookup(lambda self, *args, **kwargs: self(*args, **kwargs))
TypeError: Flask.__call__() missing 2 required positional arguments: 'environ' and 'start_response'
Traceback (most recent call last):
  File "/Users/matthew/Documents/Syncthing/MacDefault/fast-unit-flask/mwe2.py", line 22, in <module>
    r.raise_for_status()
  File "/Users/matthew/Documents/Syncthing/MacDefault/fast-unit-flask/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://my_app/complex
```

I'm not sure if this is related to whether I pass `base_url` to `Session` or not.

**Comment by mdavis-xyz** [comment]
This is possibly related: https://flask.palletsprojects.com/en/2.2.x/reqcontext/#manually-push-a-context

> This should typically only happen when testing code that expects an active request. One option is to use the [test client](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.test_client) to simulate a full request. Or you can use [test_request_context()](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.test_request_context) in a with block, and everything that runs in the block will have access to [request](https://flask.palletsprojects.com/en/2.2.x/api/#flask.request), populated with your test data.

I'm struggling to understand the code in this library. Why didn't you use a werkzeug test client? Can we replace some code in this library with a werkzeug test client to resolve this issue? I'm not sure which lines.

**Comment by mdavis-xyz** [comment]
I tried changing  this line:

https://github.com/maarten-dp/requests-flask-adapter/blob/9ce4113db19127684be1d9556e463270efc6c233/requests_flask_adapter/adapter.py#L50

to 

```
        client = self.app.test_client()
        rv = client.run_wsgi_app(environ) #, buffered=True)
```

That gave the same result.

**Comment by mdavis-xyz** [comment]
Oddly though, `flask.request` gets proxied fine.


```
from requests_flask_adapter import Session
from flask import Blueprint, Flask, current_app, request

app = Flask(__name__)
@app.route('/simple')
def simple():
    return ("Hello World", 200)


@app.route('/echo')
def body():
    data = request.get_json()
    name = data['name']
    return (f"Hello {name}", 200)

@app.route('/complex')
def complex():
    current_app()
    return ("Hello World", 200)

    
Session.register('http://my_app', app, base_url='http://my_app')
s = Session()

r=s.get('http://my_app/simple')
r.raise_for_status()


r=s.get('http://my_app/echo', json={'name': 'matt'})
r.raise_for_status()
assert 'matt' in r.text

# r=s.get('http://my_app/complex')
# r.raise_for_status()
```

**Comment by mdavis-xyz** [comment]
`flask.request` is defined here:

https://github.com/pallets/flask/blob/3a35977d5fbcc424688d32154d250bc0bae918d6/src/flask/globals.py#L78-L80

Compared to `current_app` here:

https://github.com/pallets/flask/blob/3a35977d5fbcc424688d32154d250bc0bae918d6/src/flask/globals.py#L59-L61

Those definitions look the same. Although the relevant `unbound_message` differs.

The error message for the app one mentions `app.app_context()`. [The docs for that](https://flask.palletsprojects.com/en/2.2.x/api/?highlight=before_request#flask.Flask.app_context) say:

> An application context is automatically pushed by RequestContext.push() when handling a request, and when running a CLI command. Use this to manually create a context outside of these situations.

Yet we have a request context and no app context. How did we get a request context?

**Comment by maarten-dp** [comment]
Hey! Thanks for all the info. You've caught me at a busy time. I'll look into to it as soon as I can :D

**Comment by mdavis-xyz** [comment]
Have you had a chance to look at this yet?

**Comment by maarten-dp** [comment]
Hey,

In your code you wrote `current_app()` whereas the current_app is not callable, it should be `current_app`. If you make this adjustment, your code should work.

Kind regards,
Maarten

**Comment by mdavis-xyz** [comment]
Ah yes, that's right. Silly me. I'm not sure how I missed that.

Strange, I would have expected an error message:

> TypeError: 'AppProxy' object is not callable

Oh well, I've got something working now. Thanks.
